@extends('layouts.app')
@section('content')
<div class="bg-white rounded-2xl shadow-sm border border-gray-100 p-8">
  <div class="mb-8 border-b border-gray-100 pb-6">
    <h2 class="text-3xl font-bold text-gray-800">Sejarah STAIMAS Wonogiri</h2>
  </div>
  <div class="prose prose-gray max-w-none text-gray-600 leading-loose text-justify space-y-4">
    <p>Sejarah berdirinya Sekolah Tinggi Agama Islam Mulia Astuti (STAIMAS) Wonogiri yaitu diawali dengan berdirinya Yayasan Karya Emas Center karena keinginan berkontribusi dalam pembangunan di bidang pendidikan, khususnya Pendidikan Tinggi Agama Islam sebagai bentuk partisipasi dan usaha membangun satu kebersamaan dalam mewujudkan Wonogiri Sukses, beriman, dan berkeadilan. Selain itu, kekosongan Perguruan Tinggi Agama Islam (PTAI) di Kabupaten Wonogiri menjadikan peluang didirikannya STAIMAS Wonogiri. Keberadaan perguruan tinggi Islam Wonogiri ini diharapkan menjadi tempat putra-putri Wonogiri dan sekitarnya untuk menimba ilmu guna membingkai masyarakat yang religius dan intelek untuk membangun Indonesia. Para pendiri yayasan yaitu Drs. H. Agus Mulyadi, M.H., Drs. H. Rusyidi Mansur, M.Si., Hj. Endang Maria Astuti, S.Ag. SH.MH., Drs. H. Mardi Widodo merupakan pengelola pondok pesantren Al Barru Wonogiri serta pembina beberapa pondok pesantren yang ada di Wonogiri. Karena inilah, para pendiri yayasan merasa perlu menyediakan saluran pendidikan tinggi Islam jenjang strata 1 bagi santri pondok pesantren yang telah lulus dengan dengan pertimbangan mudah dijangkau secara akses maupun materiil. Di samping itu, para pendiri yayasan juga aktif terlibat dalam berbagai kegiatan sosial kemasyarakatan, advokasi, pemberdayaan, penguatan ekonomi masyarakat, dan pengamanan social sehingga dibutuhkan suatu institusi yang dapat mengembangkan ide dan gagasan demi memajukan daerah, terutama gagasan pembangunan daerah berbasis aset lokal. Berdasarkan hal tersebut, para pendiri bersepakat mendirikan yayasan sebagai institusi yang menyelenggarakan pendidikan tinggi sekaligus mewadahi aktifitas sosial yang selama ini melekat pada para pendiri. Beberapa pertimbangan dipilihnya institusi dalam bentuk sekolah tinggi agama islam karena terkait dengan semangat dakwah, pengembangan ilmu, dan keinginan berkolaborasi dengan stakeholder pendidikan tinggi agama lain yang lebih dulu berdiri di Wonogiri yaitu Sekolah Tinggi Agama Buddha Negeri (STABN) Raden Wijaya dan Sekolah Tinggi Agama Kristen (STAK) Bina Muda Wirawan Wonogiri.</p>
    <p>Ada empat prodi yang dipilih dalam pendirian perguruan tinggi ini dengan pertimbangan masing-masing, yaitu Prodi Pendidikan Agama Islam (PAI), Prodi Komunikasi dan Penyiaran Islam (KPI), Prodi Ekonomi Syariah, dan Prodi Hukum dan Tata Negara (HTN).</p>
    <p><em>Pertama</em>, Prodi Pendidikan Agama Islam (PAI) didirikan karena profil guru agama atau ustadz dan ustadzah di Wonogiri banyak yang belum S1 sedangkan lembaga pendidikan baik formal (sekolah dan pondok pesantren) maupun nonformal semakin meningkat dan membutuhkan pendidik agama islam yang kompeten dan tersertifikasi Sarjana Pendidikan Islam. Selain itu, sekolah-sekolah di Wonogiri mulai bersaing dengan cara menawarkan program-program unggulan seperti tahfidz, membaca kitab kuning, dll sehingga dibutuhkan seorang Pengembang Bahan Ajar yang mempu menyusun metode atau bahan ajar yang menarik.</p>
    <p>Kebutuhan akan sarjana Komunikasi dan Penyiaran Islam di Wonogiri sangat tinggi. Hal tersebut sejalan dengan data ratusan Penyuluh Agama Islam Non PNS di Wonogiri rata-rata masih lulusan SMA, sedangkan per tahun 2017 Kemenag Wonogiri mulai mensyaratkan dan membutuhkan penyuluh bergelar Sarjana S1 Keagamaan Non kependidikan yaitu Sarjana Komunikasi Islam. Berkembangnya media lokal di Kabupaten Wonogiri (Radio Gajah Mungkur, GIS, Wonogiri FM, Radio Siaran Pemerintah Daerah, Global FM), stasiun TV lokal (TVRI Yogyakarta, Jogja TV, MTA TV, LDII TV, TATV), dan TV Nasional membutuhkan kontributor daerah untuk produksi konten lokal di Wonogiri. Apalagi fakta demografi 98% penduduk Wonogiri adalah muslim, dibutuhkan professional yang tidak hanya paham ilmu penyiaran tetapi juga paham agama dan mampu berdakwah. Selain itu, menjadi konten kreator yang islami dan berkualitas di media social seperti youtube dan blog juga menjadi semakin diminati oleh generasi saat ini. Namun demikian, pendidikan tinggi di bidang Komunikasi dan Penyiaran Islam belum ada di Kabupaten Wonogiri sehingga masyarakat Wonogiri yang sebagian besar ekonominya masih menengah ke bawah, mengalami kesulitan akses dan biaya. Oleh karena itu, perlu didirikan Prodi Komunikasi dan Penyiaran Islam untuk memenuhi kebutuhan pemerintah, swasta, dan masyarakat Wonogiri terhadap sarjana S1 KPI.</p>
    <p><em>Ketiga, </em>Prodi Ekonomi Syariah didirikan karena lembaga keuangan syariah nonbank seperti BMT semakin meningkat jumlahnya di Kabupaten Wonogiri, sedangkan tenaga ahli di lembaga koperasi islam ini masih banyak yang lulusan SMA dan sarjana ekonomi umum. Ini menjadi kotradiktif sehingga lembaga keuangan islam membutuhkan tenaga ahli yang kompeten dan professional dalam bidang ekonomi atau keuangan syariah. Sejak diberlakukan Dana Desa tahun 2015, Pemerintah Desa se-Kabupaten Wonogiri kekurangan perangkat desa yang kompeten untuk menyusun laporan keuangan dana desa serta memaksimalkan pengelolaan BUMDes berdasarkan karifan lokal. Apalagi potensi alam Kabupaten Wonogiri sangat cocok menjadi kawasan <em>halal tourism</em>. Oleh karena itu, dibutuhkan lulusan ekonomi syariah yang mampu mengelola keuangan dan mengelola ekonomi pembangunan pemerintah daerah maupun pemerintah desa di Kabupaten Wonogiri. Selain itu, industry halal yang saat ini popular dan terus berkembang di dunia bisnis, belum terealisasi di Wonogiri, sehingga Wonogiri membutuhkan pebisnis yang memahami prinsip-prinsip syariah dan melek digital.</p>
    <p>Seiring dengan perkembangan geo politik nasional yang ditandai dengan partai politik berbasiskan massa Islam, peraturan daerah berperspektif syariah (perda alkohol, prostitusi, perjudian, tempat hiburan, dll), maka proses pembaharuan hukum tata negara menjadi sangat urgen. Namun, pendidikan tinggi hukum tata negara hingga tingkat karisidenan Surakarta belum ada. Sebagai tanggung jawab dalam mengembangkan ilmu hukum ketatanegaraan, perlu didirikan Prodi Hukum Tatanegara (Siyasah) untuk menghasilkan tenaga ahli professional yang memiliki pemahaman yang baik tentang hukum Islam guna merancang peraturan daerah maupun peraturan tingkat desa serta memecahkan permasalahan hukum bidang tata negara di masyarakat sehingga tercipta pembangunan yang adil dan sejahtera, khususnya di Kabupaten Wonogiri.</p>
    <p>Harapan yang mulia dari para pendiri ini kemudian dijadikan nama yang melekat pada perguruan tinggi. Harapan ini menjadi sebuah doa yang dalam Bahasa Sansekerta yaitu astuti. Jadi berdirinya perguruan tinggi ini merupakan <strong>doa yang mulia</strong> agar nantinya dapat memenuhi kebutuhan masyarakat, pemerintah, swasta sehingga semua pihak bersinergi membangun Wonogiri. Atas dasar itu, sekolah tinggi ini diberi nama Sekolah Tinggi Agama Islam "Mulia Astuti" yang berarti doa/harapan yang mulia/luhur dan disingkat menjadi STAIMAS.</p>
    <p>Setelah permohonan pendirian STAIMAS Wonogiri diajukan, kemudian dilakukan visitasi oleh tim dari Direktorat Pendidikan Tinggi Islam. Untuk memaparkan niatan dan distingsi prodi yang diajukan, Pengurus Yayasan Karya Emas Center (dalam hal ini Harun Abdul Khafizh, M.Pd. dan H. Tri Gunawan Hadi, S.Sos. S.Pd.I. M.Si. MH) diterima langsung oleh Dirjend. Pedidikan Islam.</p>
    <p>Berdasarkan SK DIRJEN PENDIS Nomor 4536 TAHUN 2017 berdirilah Sekolah Tinggi Agama Islam MULIA ASTUTI yang beralamatkan di Jl Cempaka VI Pokoh RT 02 RW 04 Kelurahan Wonoboyo, STAIMAS Wonogiri membuka empat Program Studi yaitu :</p>
    <ol class="list-decimal pl-8 space-y-1">
      <li>Program Ekonomi Syariah (ES)</li>
      <li>Program Studi Komunikasi dan Penyiaran Islam (KPI)</li>
      <li>Program Studi Syiasah Syariah (Hukum Tata Negara)</li>
      <li>Program Studi Pendidikan Agama Islam (PAI)</li>
    </ol>
    <p>Rencana Strategis STAIMAS Tahun 2017-2021 yaitu Tahapan Penataan Akademik Dan Kelembagaan memiliki 9 sasaran strategis. Beberapa di antaranya yang telah tercapai adalah:</p>
    <ol class="list-decimal pl-8 space-y-1">
      <li>Meningkatnya jumlah pendaftar dan prestasi mahasiswa.</li>
      <li>Terealisasinya kegiatan pendidikan dan pembelajaran yang sesuai dengan SN Dikti dengan ciri khas religius kekaryaan.</li>
      <li>Terealisasinya penelitian dan pengabdian kepada masyarakat yang terpublikasi.</li>
      <li>Tercapainya jumlah ideal tenaga pendidik dan kependidikan perguruan tinggi.</li>
      <li>Terbangunnya sarana-prasarana utama penunjang kegiatan akademik, non akademik, dan kemahasiswaan.</li>
      <li>Tercapainya jumlah dan realisasi kerjasama akademik tingkat regional, nasional, dan internasional.</li>
      <li>Memiliki anggaran perguruan tinggi untuk mendukung proses pembelajaran.</li>
      <li>Terselenggara tata kelola dan tata pamong perguruan tinggi.</li>
    </ol>
    <p>Sedangkan sasaran strategis yang belum tercapai adalah perguruan tinggi dan seluruh program studi belum terakreditasi karena tenaga pendidik yang kurang memenuhi kualifikasi, program studi belum melakukan review kurikulum, dan auditor belum baru mengikuti pelatihan Audit Mutu Internal. Seluruh akar masalah ini mulai diperbaiki tahun 2021 setelah pelaksanaan akreditasi.</p>
    <p>Rencana Strategis STAIMAS Tahun 2022-2026 ini merupakan perwujudan RIP tahap ke-2 yaitu Tahap Penguatan Akademik dan Kelembagaan STAIMAS Wonogiri. Pada tahap ini, sasaran utama STAIMAS adalah menguatnya berbagai aspek akademik dan kelembagaan seperti implementasi kurikulum Kampus Merdeka, menambah sarana prasarana, peningkatan kualifikasi dosen, akreditasi institusi dan program studi, peningkatan jumlah dan mutu penelitian/publikasi ilmiah, pembinaan mahasiswa, dan sebagainya, sehingga mampu bersaing di tingkat regional (Eks Karisidenan Surakarta).</p>
    <p>Terdapat sembilan sasaran strategis yang ingin dicapai pada tahap ini, yaitu:</p>
    <ol class="list-decimal pl-8 space-y-1">
      <li>Terwujudnya tata kelola dan tata pamong STAIMAS yang didukung oleh sistem aplikasi berbasis ICT.</li>
      <li>Seluruh prodi memperoleh akreditasi Baik.</li>
      <li>Meningkatnya jumlah dan realisasi kerjasama akademik tingkat nasional dan internasional.</li>
      <li>Meningkatnya jumlah pendaftar, mutu, dan prestasi mahasiswa, serta mutu dan daya saing lulusan STAIMAS.</li>
      <li>Tercapainya jumlah ideal, kualifikasi yang sesuai, dan kinerja yang professional tenaga pendidik dan kependidikan STAIMAS.</li>
      <li>Meningkatnya jumlah pendanaan perguruan tinggi untuk mendukung proses pembelajaran.</li>
      <li>Terbangunnya sarana-prasarana utama penunjang kegiatan akademik, non akademik, dan kemahasiswaan.</li>
      <li>Terealisasinya kegiatan pendidikan dan pembelajaran yang bermutu sesuai dengan standar nasional pendidikan tinggi dengan ciri khas religius kekaryaan.</li>
      <li>Meningkatnya jumlah dan mutu hasil penelitian dan pengabdian kepada masyarakat yang terpublikasi secara nasional.</li>
    </ol>
  </div>
</div>
@endsection
